#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------
# Configurable
# ------------------------------------------------------------------

# Directory of this script (portable).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The wrk repo root — assumed to be the parent of scripts/.
WRK_REPO="$(cd "$SCRIPT_DIR/.." && pwd)"

WRK_DEMO_DIR="${WRK_DEMO_DIR:-$(cd "$WRK_REPO/.." && pwd)/wrk-demo}"
WRK_BIN="${WRK_BIN:-$WRK_REPO/bin/wrk}"

# Where wrk actually stores things (mirrors app.DefaultStorage()).
WRK_STORAGE="${XDG_DATA_HOME:-$HOME/Library/Application Support}/wrk/repositories"

# Anchor for safety checks.
DEMO_PARENT="$(dirname "$WRK_DEMO_DIR")"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

say()  { printf "\033[1;36m▶\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m!\033[0m %s\n" "$*" >&2; }
die()  { printf "\033[1;31m✗\033[0m %s\n" "$*" >&2; exit 1; }

require_wrk() {
  [[ -x "$WRK_BIN" ]] || die "wrk binary not found at $WRK_BIN — run 'just build' first"
}

# Refuse to rm -rf anything outside the demo parent.
safe_rm() {
  local target="$1"
  local resolved
  resolved="$(cd "$(dirname "$target")" 2>/dev/null && pwd)/$(basename "$target")" || {
    return 0 # already gone
  }
  case "$resolved" in
    "$DEMO_PARENT"/*)
      rm -rf "$resolved"
      ;;
    *)
      die "refusing to remove $resolved (outside $DEMO_PARENT)"
      ;;
  esac
}

# ------------------------------------------------------------------
# Subcommands
# ------------------------------------------------------------------

cmd_setup() {
  require_wrk

  [[ ! -e "$WRK_DEMO_DIR" ]] || die "$WRK_DEMO_DIR already exists — use 'reset' or remove it first"

  say "creating $WRK_DEMO_DIR"
  mkdir -p "$WRK_DEMO_DIR"
  cd "$WRK_DEMO_DIR"

  say "initializing jj (colocated with git)"
  git init -b main
  jj git init --colocate >/dev/null

  say "writing tracked project files"

  cat > .gitignore <<'EOF'
.env
node_modules
.wrk.local.yml
EOF

  cat > package.json <<'EOF'
{
  "name": "wrk-demo",
  "version": "0.1.0",
  "dependencies": {
    "left-pad": "1.3.0"
  }
}
EOF

  cat > yarn.lock <<'EOF'
# demo yarn.lock — content is what fingerprinting hashes
left-pad@1.3.0: {}
EOF

  cat > README.md <<'EOF'
# wrk-demo

A synthetic project for manually testing `wrk`. Regenerated by
`scripts/demo.sh setup`.
EOF

  cat > src.txt <<'EOF'
hello from wrk-demo
EOF

  say "writing .wrk.yml"
  cat > .wrk.yml <<'EOF'
resources:
  - name: env
    path: .env
    create: false

  - name: node
    path: node_modules
    fingerprint:
      - "{root}/package.json"
      - "{root}/yarn.lock"
    hooks:
      initialize:
        # Ensure the fingerprint-specific shared directory exists...
        - run: mkdir -p "{shared}"
          cwd: "{root}"
        # ...and drop a marker so we can verify the hook actually ran.
        - run: touch "{shared}/INSTALLED"
          cwd: "{root}"
EOF

  say "writing .wrk.local.yml (demonstrates same-name override)"
  cat > .wrk.local.yml <<'EOF'
resources:
  # Personal-only resource.
  - name: envrc
    path: .envrc
    create: false
EOF

  say "creating an untracked .env for wrk to adopt"
  cat > .env <<'EOF'
API_KEY=demo-key
EOF

  say "making an initial commit"
  git add -A
  git -c user.email=demo@example.com -c user.name=demo commit -q -m "initial demo"

  say "done. Try:"
  cat <<EOF

  cd $WRK_DEMO_DIR
  $WRK_BIN link
  $WRK_BIN status
  $WRK_BIN workspaces

Or add a linked workspace:

  $(basename "$0") add-workspace feature

Or run a wrk command without cd:

  $(basename "$0") run link --dry-run

EOF
}

cmd_teardown() {
  # Compute the repository id the way wrk does (local/<hash>) so we can
  # scrub the shared-storage entry surgically.
  if [[ -d "$WRK_DEMO_DIR/.git" ]]; then
    local gitdir
    gitdir="$(cd "$WRK_DEMO_DIR" && git rev-parse --git-common-dir)"
    if [[ ! "$gitdir" = /* ]]; then
      gitdir="$WRK_DEMO_DIR/$gitdir"
    fi
    local hash
    hash="$(printf '%s' "$gitdir" | shasum -a 256 | cut -c1-16)"
    local storage_entry="$WRK_STORAGE/local/$hash"

    if [[ -d "$storage_entry" ]]; then
      say "removing shared storage entry $storage_entry"
      # Absolute path safety: must live under WRK_STORAGE.
      case "$storage_entry" in
        "$WRK_STORAGE"/*) rm -rf "$storage_entry" ;;
        *) die "refusing to remove $storage_entry" ;;
      esac
    fi
  fi

  if [[ -e "$WRK_DEMO_DIR" ]]; then
    say "removing $WRK_DEMO_DIR"
    safe_rm "$WRK_DEMO_DIR"
  fi

  # Also remove any linked worktrees under the demo parent that we own.
  # We only touch dirs whose names start with wrk-demo-.
  local sibling
  for sibling in "$DEMO_PARENT"/wrk-demo-*; do
    [[ -e "$sibling" ]] || continue
    say "removing linked workspace $sibling"
    safe_rm "$sibling"
  done

  say "teardown complete"
}

cmd_reset() {
  cmd_teardown
  cmd_setup
}

cmd_add_workspace() {
  require_wrk
  local name="${1:-}"
  [[ -n "$name" ]] || die "usage: $(basename "$0") add-workspace <name>"

  local dest="$DEMO_PARENT/wrk-demo-$name"
  [[ ! -e "$dest" ]] || die "$dest already exists"

  cd "$WRK_DEMO_DIR"
  say "creating linked workspace at $dest"
  "$WRK_BIN" new "$dest"

  say "workspace ready. Try:"
  echo "  cd $dest && $WRK_BIN status"
}

cmd_run() {
  require_wrk
  [[ -d "$WRK_DEMO_DIR" ]] || die "$WRK_DEMO_DIR does not exist — run 'setup' first"
  (cd "$WRK_DEMO_DIR" && "$WRK_BIN" "$@")
}

cmd_state() {
  echo "demo dir: $WRK_DEMO_DIR ($( [[ -e "$WRK_DEMO_DIR" ]] && echo present || echo absent))"
  echo "wrk bin:  $WRK_BIN ($( [[ -x "$WRK_BIN" ]] && echo present || echo missing))"
  echo

  if [[ -d "$WRK_DEMO_DIR" ]]; then
    echo "workspaces:"
    (cd "$WRK_DEMO_DIR" && "$WRK_BIN" workspaces 2>/dev/null) || echo "  (wrk workspaces failed)"
    echo

    echo "shared storage under wrk:"
    local gitdir hash entry
    gitdir="$(cd "$WRK_DEMO_DIR" && git rev-parse --git-common-dir 2>/dev/null || true)"
    if [[ -n "$gitdir" ]]; then
      [[ "$gitdir" = /* ]] || gitdir="$WRK_DEMO_DIR/$gitdir"
      hash="$(printf '%s' "$gitdir" | shasum -a 256 | cut -c1-16)"
      entry="$WRK_STORAGE/local/$hash"
      if [[ -d "$entry" ]]; then
        find "$entry" -maxdepth 3 -print | sed "s|$entry|  ...|"
      else
        echo "  (no storage entry for local/$hash)"
      fi
    fi
  fi
}

cmd_help() {
  cat <<EOF
usage: $(basename "$0") <command> [args]

Commands:
  setup               Create the demo repo at $WRK_DEMO_DIR
  teardown            Remove the demo repo and its shared storage entry
  reset               teardown && setup
  add-workspace NAME  Create a linked workspace at ${DEMO_PARENT}/wrk-demo-NAME
  run [wrk args...]   Run 'wrk <args>' inside the demo repo
  state               Show a summary of what exists on disk
  help                Show this help 

Here's the rest of the script:

```bash
Environment variables:
  WRK_DEMO_DIR   Where the demo lives (default: $WRK_DEMO_DIR)
  WRK_BIN        Path to the wrk binary (default: $WRK_BIN)

Examples:
  $(basename "$0") setup
  $(basename "$0") run link
  $(basename "$0") run status
  $(basename "$0") add-workspace feature
  $(basename "$0") run --vcs jj workspaces
  $(basename "$0") reset

EOF
}

# ------------------------------------------------------------------
# Dispatch
# ------------------------------------------------------------------

case "${1:-help}" in
  setup)          shift; cmd_setup "$@" ;;
  teardown)       shift; cmd_teardown "$@" ;;
  reset)          shift; cmd_reset "$@" ;;
  add-workspace)  shift; cmd_add_workspace "$@" ;;
  run)            shift; cmd_run "$@" ;;
  state)          shift; cmd_state "$@" ;;
  help|-h|--help) cmd_help ;;
  *)              die "unknown command: $1 (try 'help')" ;;
esac
